footer:
  logo_link: /en/
  social: |
    [[:facebook: Facebook]](https://www.facebook.com/inSpiritsBar/ "[nofollow light-dot-sm]")
    [[:youtube: Youtube]](https://www.youtube.com/channel/UCqPuR4adIHXpFPkah7fhC3g "[nofollow light-dot-sm]")
    [[:instagram: Instagram]](https://www.instagram.com/inspirits_bar/ "[nofollow light-dot-sm]")
  pages: |
    [Pages](/en/sitemap/ "[nofollow]")
    {.h2}
    - [Home](/en/)
    - [Sustainability](/en/sustainability/)
    - [About Us](/en/about-us/)
    - [FAQ](/en/faq/)
    - [Blog](/en/blog/)
  services: |
    [Services](/en/services/ "[nofollow]")
    {.h2}
    - [Coffee Bar](/en/service/coffee/)
    - [Cocktail Bar](/en/service/cocktails/)
    - [Smoothies & More](/en/service/smoothies/)
    - [Trade Show Service](/en/service/messe/)
    - [All from one source](/en/service/others/)
  contact: |
    [Contact](/en/contact/)
    {.h2}
    - :alt-phone: [+49 89 97861114](tel:+498997861114 "[nofollow ga4]")
    - :envelope: [info@inspiritsbar.de](mailto:info@inspiritsbar.de "[ga4]")
    - :location-dot: [Johann-Karg-Straße <br> 30, 85540 Haar](https://maps.app.goo.gl/Cst8Q4sHjYme6sCaA "[nofollow ga4]")

    [[Contact us!]](/en/contact/)
  legal: |
    - [© {{< year >}} inspirits](/en/)
    - {{< internal-link legal >}}
    - {{< internal-link privacy >}}
    - {{< internal-link cookies >}}
    - {{< langs alt-globe >}}
    {.list-inline}

    ~Made with :heart: by [seacomoseo.com](https://seacomoseo.com/ "[homefollow]")~
